

CREATE TABLE TimeCardsAudits(
	[AuditId] [int] primary key IDENTITY(1,1) NOT NULL,
	[TimeCardId] [int] NOT NULL,
	[CompanyCodeId] [int] NOT NULL,
	[EmployeeId] [int] NOT NULL,
	[ActualDate] [date] NOT NULL,
	[ProjectNumber] [int] NOT NULL,
	[DailyHours] [float] NULL,
	[HoursCodeId] [int] NULL,
	[Hours] [float] NULL,
	[EarningsCodeId] [int] NULL,
	[EarningsAmount] [float] NULL,
	[TempDeptId] [int] NULL,
	[TempJobId] [int] NULL,
	[TimeIn] [datetime] NULL,
	[TimeOut] [datetime] NULL,
	[LunchOut] [datetime] NULL,
	[LunchBack] [datetime] NULL,
	[IsApproved] [bit] NOT NULL,
	[ApprovedBy] [varchar](50) NULL,
	[HoursCodeReasonId] [int] NULL,
	[FileNumber] [nvarchar](50) NULL,
	[Project] [varchar](70) NULL,
	[Task] [varchar](70) NULL,
	[OT] [float] NULL,
	[MealsTaken] [int] NULL,
	[Rate] [float] NULL,
	[HoursCodeRate] [float] NULL,
	[EnteredBy] [varchar](50) NULL,
	[EnteredDate] [datetime] NULL,
	[DepartmentId] [int] NULL,
	[JobId] [int] NULL,
	[FundsId] [int] NULL,
	[ProjectsId] [int] NULL,
	[TaskId] [int] NULL,
	[PositionId] [int] NULL,
	[UserId] [varchar](100) NULL,
	[LastModifiedDate] [datetime] NULL,
	[AuditUserId] [varchar](50),
	[AuditType] [varchar](50),
	[AuditRecType ] [varchar](50),
	[AuditDate] [datetime] DEFAULT GETDATE()
	)


