CREATE TABLE [dbo].[E_Positions] (
    [E_PositionId]          INT             IDENTITY (1, 1) NOT NULL,
    [EmployeeId]            INT             NOT NULL,
    [PositionId]            INT        NOT NULL,
    [PayFrequencyId]        int         NULL,
    [RateTypeId]            INT             NULL,
    [PrimaryPosition]       BIT             CONSTRAINT [DF_E_Positions_PrimaryPosition] DEFAULT ((1)) NULL,
    [StartDate]             DATETIME   NULL,
    [EndDate]               DATETIME   NULL,
    [Notes]                 TEXT            NULL,
    [EnteredBy]             VARCHAR (50)    NULL,
    [EnteredDate]           DATETIME   NULL,
    [ModifiedBy]            VARCHAR (50)    NULL,
    [ModifiedDate]          DATETIME   NULL,
    [projectedEndDate]      DATETIME   NULL,
    [actualEndDate]         DATETIME   NULL,
    [positionCategoryID]    INT             NULL,
    [positionTypeID]        INT        NULL,
    [positionGradeID]       INT        NULL,
    [scheduledDays]         VARCHAR (9)     NULL,
    [weeklyHours]           VARCHAR (9)     NULL,
    [salary]                MONEY           NULL,
    [determinedStatus]      VARCHAR (50)    NULL,
    [headcount]             DECIMAL (18)    NULL,
    [FTE]                   DECIMAL (18)    NULL,
    [homeDepartmentID]      INT             NULL,
    [homeLocationID]        INT             NULL,
    [percentage]            DECIMAL (18, 2) NULL,
    [payRate]               MONEY           NULL,
    [rateTypeCode]          VARCHAR (1)     NULL,
    [overtimeMultiplier]    DECIMAL (18, 2) NULL,
    [shift]                 TINYINT         NULL,
    [clockNumber]           VARCHAR (50)    NULL,
    [workersCompensationID] TINYINT         NULL,
    [FLSAID]                TINYINT         NULL,
    [companyID]             INT             NULL,
    [payFrequencyCode]      VARCHAR (10)    NULL,
    [mustAllocate]          BIT             NULL,
    [Class]                 VARCHAR (10)    NULL,
    [ReportsToID]           VARCHAR (9)     NULL,
    [GoalAmount]            MONEY           NULL,
    [spaceNumber]           VARCHAR (50)    NULL,
    CONSTRAINT [PK_E_Positions] PRIMARY KEY CLUSTERED ([E_PositionId] ASC),
    CONSTRAINT [FK_E_Positions_DdlPayFrequencies] FOREIGN KEY ([PayFrequencyId]) REFERENCES [dbo].[DdlPayFrequencies] ([PayFrequencyId]),
    CONSTRAINT [FK_E_Positions_DdlRateTypes] FOREIGN KEY ([RateTypeId]) REFERENCES [dbo].[DdlRateTypes] ([RateTypeId]),
    CONSTRAINT [FK_E_Positions_Employees] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employees] ([EmployeeId]) ON DELETE CASCADE,
    CONSTRAINT [FK_E_Positions_Positions] FOREIGN KEY ([PositionId]) REFERENCES [dbo].[Positions] ([PositionId])
);

