CREATE TABLE [dbo].[Employees] (
    [EmployeeId]              INT             IDENTITY (1, 1) NOT NULL,
    [PersonId]                INT             NOT NULL,
    [CompanyCode]             VARCHAR (50)    NULL,
    [Rate]                    DECIMAL (18, 4) NULL,
    [RateTypeId]              INT             NULL,
    [FileNumber]              VARCHAR (50)    NULL,
    [EmploymentNumber]        INT         NOT NULL,
    [EmploymentStatusId]      INT         NULL,
    [HireDate]                DATETIME   NOT NULL,
    [TerminationDate]         DATETIME   NULL,
    [PlannedServiceStartDate] DATETIME   NULL,
    [ActualServiceStartDate]  DATETIME   NULL,
    [EmployeeTypeID]          INT        NULL,
    [ProbationEndDate]        DATETIME   NULL,
    [TrainingEndDate]         DATETIME   NULL,
    [SeniorityDate]           DATETIME   NULL,
    [PayFrequencyId]          int         NULL,
    [FedExemptions]           CHAR (2)        NULL,
    [WorkedStateTaxCodeId]    INT         NULL,
    [MaritalStatusID]         INT             NULL,
    [Hours]                   DECIMAL (18, 2) NULL,
    [EnteredBy]               VARCHAR (50)    NULL,
    [EnteredDate]             DATETIME   NULL,
    [ModifiedBy]              VARCHAR (50)    NULL,
    [ModifiedDate]            DATETIME   NULL,
    [DepartmentId]            INT        NULL,
    [CompanyCodeId]           INT        NULL,
    [TimeCardTypeId]          INT        DEFAULT ((3)) NULL,
    CONSTRAINT [PK_eEmployees] PRIMARY KEY CLUSTERED ([EmployeeId] ASC),
    CONSTRAINT [FK_Employees_DdlEmployeeTypes] FOREIGN KEY ([EmployeeTypeID]) REFERENCES [dbo].[DdlEmployeeTypes] ([EmployeeTypeId]),
    CONSTRAINT [FK_Employees_DdlEmploymentStatuses] FOREIGN KEY ([EmploymentStatusId]) REFERENCES [dbo].[DdlEmploymentStatuses] ([EmploymentStatusId]),
    CONSTRAINT [FK_Employees_DdlMaritalStatuses] FOREIGN KEY ([MaritalStatusID]) REFERENCES [dbo].[DdlMaritalStatuses] ([MaritalStatusId]),
    CONSTRAINT [FK_Employees_DdlPayFrequencies] FOREIGN KEY ([PayFrequencyId]) REFERENCES [dbo].[DdlPayFrequencies] ([PayFrequencyId]),
    CONSTRAINT [FK_Employees_DdlRateTypes] FOREIGN KEY ([RateTypeId]) REFERENCES [dbo].[DdlRateTypes] ([RateTypeId]),
    CONSTRAINT [FK_Employees_DdlStates] FOREIGN KEY ([WorkedStateTaxCodeId]) REFERENCES [dbo].[DdlStates] ([StateId]),
    CONSTRAINT [FK_Employees_Departments] FOREIGN KEY ([DepartmentId]) REFERENCES [dbo].[Departments] ([DepartmentId]),
    CONSTRAINT [FK_Employees_Persons] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[Persons] ([PersonId]) ON DELETE CASCADE,
    CONSTRAINT [FK_Employees_TimeCardTypes] FOREIGN KEY ([TimeCardTypeId]) REFERENCES [dbo].[DdlTimeCardTypes] ([TimeCardTypeId])
);

