CREATE TABLE [dbo].[PersonTrainings] (
    [PersonTrainingId]   INT           IDENTITY (1, 1) NOT NULL,
    [PersonId]           INT           NOT NULL,
    [TrainingCourseId]   TINYINT       NOT NULL,
    [RecommendationDate] SMALLDATETIME NULL,
    [RequiredByDate]     SMALLDATETIME NULL,
    [ScheduledDate]      SMALLDATETIME NULL,
    [CompletedDate]      SMALLDATETIME NULL,
    [PositionCurriculum] BIT           CONSTRAINT [DF_PTrainingRequirements_positionCurriculum] DEFAULT ((0)) NULL,
    [Notes]              TEXT          NULL,
    [StartDate]          SMALLDATETIME NULL,
    [TravelCost]         MONEY         NULL,
    [HotelMealsExpense]  MONEY         NULL,
    [ActualCourseCost]   MONEY         NULL,
    [QualityRelated]     BIT           NULL,
    [OshaRelated]        BIT           NULL,
    [Venue]              VARCHAR (50)  NULL,
    [ManagerApproved]    BIT           NULL,
    [ApprovingManager]   INT           NULL,
    [EnteredBy]          VARCHAR (50)  NULL,
    [EnteredDate]        SMALLDATETIME NULL,
    [CompleteStatus]     VARCHAR (50)  CONSTRAINT [DF_PersonTrainings_CompleteStatus] DEFAULT ('incomplete') NULL,
    [Grade]              VARCHAR (3)   CONSTRAINT [DF_PersonTrainings_Grade] DEFAULT ('') NULL,
    [EnrollStatus]       VARCHAR (50)  CONSTRAINT [DF_PersonTrainings_EnrollStatus] DEFAULT ('unknown') NULL,
    CONSTRAINT [PK_pTrainingRequirements] PRIMARY KEY CLUSTERED ([PersonTrainingId] ASC),
    CONSTRAINT [FK_PersonTrainings_DdlTrainingCourses] FOREIGN KEY ([TrainingCourseId]) REFERENCES [dbo].[DdlTrainingCourses] ([TrainingCourseId]),
    CONSTRAINT [FK_PersonTrainings_Persons] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[Persons] ([PersonId])
);

