CREATE TABLE [dbo].[PersonAdditionals] (
    [PersonAdditionalId]     INT           IDENTITY (1, 1) NOT NULL,
    [PersonId]               INT           NOT NULL,
    [BirthPlace]             VARCHAR (50)  NULL,
    [EeoTypeId]              INT       CONSTRAINT [DF_pAdditional_ddlEEOTypeID] DEFAULT ((0)) NULL,
    [ApplicantSourceId]      INT           CONSTRAINT [DF_pAdditional_ddlApplicantSourceID] DEFAULT ((0)) NULL,
    [CitizenshipId]          INT      CONSTRAINT [DF_pAdditional_ddlCitizenshipID] DEFAULT ((0)) NULL,
    [CitizenshipDate]        SMALLDATETIME NULL,
    [Veteran]                VARCHAR (50)  NULL,
    [Other]                  BIT           NULL,
    [SpecialDisabled]        BIT           NULL,
    [Vietnam]                BIT           NULL,
    [Disabled]               BIT           CONSTRAINT [DF_pAdditional_disabled] DEFAULT ((0)) NOT NULL,
    [DisabledComments]       TEXT          NULL,
    [HospitalId]             INT           CONSTRAINT [DF_pAdditional_hospitalID] DEFAULT ((0)) NULL,
    [Doctor]                 VARCHAR (50)  NULL,
    [BloodDonor]             BIT           CONSTRAINT [DF_pAdditional_bloodDonor] DEFAULT ((0)) NULL,
    [Smoker]                 BIT           CONSTRAINT [DF_pAdditional_smoker] DEFAULT ((0)) NULL,
    [AdvancedDirective]      BIT           CONSTRAINT [DF_pAdditional_advancedDirective] DEFAULT ((0)) NULL,
    [EarlyRetirementDate]    SMALLDATETIME NULL,
    [NormalRetirementDate]   SMALLDATETIME NULL,
    [ExpectedRetirementDate] SMALLDATETIME NULL,
    [DateOfDeath]            SMALLDATETIME NULL,
    [Notes]                  TEXT          NULL,
    [EnteredBy]              VARCHAR (50)  NULL,
    [EnteredDate]            SMALLDATETIME NULL,
    [ModifiedBy]             VARCHAR (50)  NULL,
    [ModifiedDate]           SMALLDATETIME NULL,
    CONSTRAINT [PK_pAdditional] PRIMARY KEY CLUSTERED ([PersonAdditionalId] ASC),
    CONSTRAINT [FK_PersonAdditional_ddlApplicantSources] FOREIGN KEY ([ApplicantSourceId]) REFERENCES [dbo].[DdlApplicantSources] ([ApplicantSourceId]),
    CONSTRAINT [FK_PersonAdditional_DdlCitizenships] FOREIGN KEY ([CitizenshipId]) REFERENCES [dbo].[DdlCitizenships] ([CitizenshipId]),
    CONSTRAINT [FK_PersonAdditional_DdlEeoTypes] FOREIGN KEY ([EeoTypeId]) REFERENCES [dbo].[DdlEeoTypes] ([EeoTypeId]),
    CONSTRAINT [FK_PersonAdditional_DdlHospitals] FOREIGN KEY ([HospitalId]) REFERENCES [dbo].[DdlHospitals] ([HospitalId]),
    CONSTRAINT [FK_PersonAdditional_Persons] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[Persons] ([PersonId])
);

