CREATE TABLE [dbo].[Positions] (
    [PositionId]            INT       IDENTITY (1, 1) NOT NULL,
    [BusinessLevelNbr]      INT            NULL,
    [JobId]                 INT            NULL,
    [DepartmentId]          INT       NULL,
    [LocationId]            INT       NULL,
    [UserDefinedSegment1Id] INT       NULL,
    [UserDefinedSegment2Id] INT       NULL,
    [PositionDescription]   VARCHAR (50)   NOT NULL,
    [PositionCode]          VARCHAR (15)   NOT NULL,
    [IsPositionActive]      BIT            NOT NULL,
    [ReportsToPositionId]   INT       NULL,
    [Title]                 VARCHAR (150)  NULL,
    [CreatedDate]           DATETIME  NULL,
    [FrozenDate]            DATETIME  NULL,
    [ClosedDate]            DATETIME  NULL,
    [Status]                INT            CONSTRAINT [DF_posPositions_status] DEFAULT ((1)) NULL,
    [PositionCategoryID]    INT            CONSTRAINT [DF_posPositions_positionCategoryID] DEFAULT ((0)) NULL,
    [PositionTypeId]        INT       CONSTRAINT [DF_posPositions_positionTypeID] DEFAULT ((0)) NULL,
    [PayFrequencyCode]      VARCHAR (150)  NULL,
    [ProbationPeriod]       VARCHAR (50)   CONSTRAINT [DF_posMain_probationPeriod] DEFAULT ((0)) NULL,
    [UnitsID]               INT       CONSTRAINT [DF_posPositions_unitsID] DEFAULT ((0)) NULL,
    [ScheduledHours]        VARCHAR (50)   CONSTRAINT [DF_posMain_scheduledHours] DEFAULT ((40)) NULL,
    [LastModifiedDate]      DATETIME  NULL,
    [AuthorizedByID]        INT            CONSTRAINT [DF_posPositions_authorizedByID] DEFAULT ((0)) NULL,
    [TotalSlots]            INT        CONSTRAINT [DF_posMain_totalSlots] DEFAULT ((0)) NULL,
    [EnteredDate]           DATETIME  NULL,
    [EnteredBy]             NVARCHAR (150) NULL,
    [Requisitno]            VARCHAR (50)   NULL,
    [TravPercent]           VARCHAR (50)   NULL,
    [Shift]                 VARCHAR (50)   NULL,
    [PositReason]           VARCHAR (50)   NULL,
    [PositLocation]         VARCHAR (50)   NULL,
    [PositStatusActive]     DATETIME  NULL,
    [PositStatusFrozen]     DATETIME  NULL,
    [PositStatusClosed]     DATETIME  NULL,
    [PositStatusOpen]       DATETIME  NULL,
    [PositStatusPost]       DATETIME  NULL,
    [PerProfileID]          INT            NULL,
    [StartDate]             DATETIME  NULL,
    [ProjectEndDate]        DATETIME  NULL,
    [ActualEnddate]         DATETIME  NULL,
    [ThirdShift]            BIT            CONSTRAINT [DF_Positions_ThirdShift] DEFAULT ((0)) NULL,
    [Description]           VARCHAR (5000) NULL,
    [Code]                  VARCHAR (50)   NULL,
    [AccountNumber]         VARCHAR (50)   NULL,
    [Group2]                VARCHAR (250)  NULL,
    [Group3]                VARCHAR (250)  NULL,
    [Group4]                VARCHAR (250)  NULL,
    [Group5]                VARCHAR (250)  NULL,
    [FLSA]                  VARCHAR (50)   NULL,
    [LengthOfContract]      INT            NULL,
    [WorkClassificationId]  INT       NULL,
    [AlternateTitle]        VARCHAR (50)   NULL,
    [BusinessUnitId]        int       NULL,
    [FTE]                   INT            NULL,
    [IncumbentADPID]        VARCHAR (10)   NULL,
    [Division]              VARCHAR (50)   NULL,
    [SalaryAmount]          MONEY          NULL,
    [SalaryPlanCode]        VARCHAR (5)    NULL,
    [SalaryStep]            VARCHAR (50)   NULL,
    [SalaryType]            VARCHAR (50)   NULL,
    [SalaryPayGroup]        VARCHAR (50)   NULL,
    [PositionGradeID]       INT       NULL,
    CONSTRAINT [PK_vPositions] PRIMARY KEY CLUSTERED ([PositionId] ASC),
    CONSTRAINT [FK_Positions_BusinessUnits] FOREIGN KEY ([BusinessUnitId]) REFERENCES [dbo].[BusinessUnits] ([BusinessUnitId]),
    CONSTRAINT [FK_Positions_DdlEmployeeTypes] FOREIGN KEY ([WorkClassificationId]) REFERENCES [dbo].[DdlEmployeeTypes] ([EmployeeTypeId]),
    CONSTRAINT [FK_Positions_DdlPositionCategory] FOREIGN KEY ([PositionCategoryID]) REFERENCES [dbo].[DdlPositionCategories] ([PositionCategoryID]),
    CONSTRAINT [FK_Positions_DdlPositionTypes] FOREIGN KEY ([PositionTypeId]) REFERENCES [dbo].[ddlPositionTypes] ([PositionTypeId]),
    CONSTRAINT [FK_Positions_Departments] FOREIGN KEY ([DepartmentId]) REFERENCES [dbo].[Departments] ([DepartmentId]),
    CONSTRAINT [FK_POSITIONS_JOBS] FOREIGN KEY ([JobId]) REFERENCES [dbo].[Jobs] ([JobId]),
    CONSTRAINT [FK_Positions_Locations] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Locations] ([LocationId]),
    CONSTRAINT [FK_Positions_PerformanceProfiles] FOREIGN KEY ([PerProfileID]) REFERENCES [dbo].[PerformanceProfiles] ([PerProfileID]),
    CONSTRAINT [FK_POSITIONS_PositionBusinessLevels] FOREIGN KEY ([BusinessLevelNbr]) REFERENCES [dbo].[PositionBusinessLevels] ([BusinessLevelNbr]),
    CONSTRAINT [FK_Positions_UserDefinedSegment1s] FOREIGN KEY ([UserDefinedSegment1Id]) REFERENCES [dbo].[UserDefinedSegment1s] ([UserDefinedSegment1Id]),
    CONSTRAINT [FK_Positions_UserDefinedSegment2s] FOREIGN KEY ([UserDefinedSegment2Id]) REFERENCES [dbo].[UserDefinedSegment2s] ([UserDefinedSegment2Id]),
    CONSTRAINT [uq_Positions] UNIQUE NONCLUSTERED ([PositionCode] ASC, [PositionDescription] ASC, [JobId] ASC, [BusinessLevelNbr] ASC, [Title] ASC)
);

