CREATE TABLE [dbo].[TimeCards] (
    [TimeCardId]     INT          IDENTITY (1, 1) NOT NULL,
    [CompanyCodeId]  INT     NOT NULL,
    [EmployeeId]     INT          NOT NULL,
    [ActualDate]     DATE         NOT NULL,
    [ProjectNumber]  INT          NOT NULL,
    [DailyHours]     FLOAT (53)   NULL,
    [HoursCodeId]    INT          NULL,
    [Hours]          FLOAT (53)   NULL,
    [EarningsCodeId] INT     NULL,
    [EarningsAmount] FLOAT (53)   NULL,
    [TempDeptId]     INT     NULL,
    [TempJobId]      INT          NULL,
    [TimeIn]         DATETIME     NULL,
    [TimeOut]        DATETIME     NULL,
    [LunchOut]       DATETIME     NULL,
    [LunchBack]      DATETIME     NULL,
    [IsApproved]     BIT          CONSTRAINT [DF_vTimeCard_IsApproved] DEFAULT ((0)) NOT NULL,
    [ApprovedBy]     VARCHAR (50) NULL,
	[PositionId] INT NOT NULL, 
    [DepartmentId] INT NOT NULL, 
    [FileNumber] VARCHAR(50) NULL, 
    [IsDeleted] BIT NOT NULL, 
    [UserId] VARCHAR(50) NULL, 
    CONSTRAINT [PK_TimeCards] PRIMARY KEY CLUSTERED ([TimeCardId] ASC),
    CONSTRAINT [FK_TimeCards_CompanyCodes] FOREIGN KEY ([CompanyCodeId]) REFERENCES [dbo].[CompanyCodes] ([CompanyCodeId]),
    CONSTRAINT [FK_TimeCards_Departments] FOREIGN KEY ([TempDeptId]) REFERENCES [dbo].[Departments] ([DepartmentId]),
    CONSTRAINT [FK_TimeCards_EarningsCode] FOREIGN KEY ([EarningsCodeId]) REFERENCES [dbo].[EarningsCodes] ([EarningsCodeId]),
    CONSTRAINT [FK_TimeCards_Employees] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employees] ([EmployeeId]),
    CONSTRAINT [FK_TimeCards_HoursCodes] FOREIGN KEY ([HoursCodeId]) REFERENCES [dbo].[HoursCodes] ([HoursCodeId]),
    CONSTRAINT [FK_TimeCards_Jobs] FOREIGN KEY ([TempJobId]) REFERENCES [dbo].[Jobs] ([JobId]),
    CONSTRAINT [uq_TimeCards] UNIQUE NONCLUSTERED ([CompanyCodeId] ASC, [EmployeeId] ASC, [ActualDate] ASC, [ProjectNumber] ASC)
);

